package com.sfmta.websvcs.odi11gws;

import javax.xml.ws.WebServiceRef;
// !THE CHANGES MADE TO THIS FILE WILL BE DESTROYED IF REGENERATED!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 101221.1153.15811)

public class OdiInvokeRequestSOAP11Port0Client
{
  @WebServiceRef
  private static OdiInvoke odiInvoke;

  public static void main(String [] args)
  {
    odiInvoke = new OdiInvoke();
    RequestPortType requestPortType = odiInvoke.getOdiInvokeRequestSOAP11Port0();
    // Add your code to call the desired methods.
  }
}
