package com.sfmta.websvcs.applyratexml;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.jws.soap.SOAPBinding.Style;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 101221.1153.15811)

@WebService(wsdlLocation="http://lnxappdev1:9704/axis2/services/OdiInvoke.OdiInvokeSOAP11port0/#%7Bxmlns.oracle.com%2Fodi%2FOdiInvoke%2F%7DOdiInvoke?wsdl",
  targetNamespace="xmlns.oracle.com/odi/OdiInvoke/", name="OdiInvokePortType")
@XmlSeeAlso(
  { com.sfmta.websvcs.applyratexml.types.ObjectFactory.class })
@SOAPBinding(style=Style.DOCUMENT, parameterStyle=ParameterStyle.BARE)
public interface OdiInvokePortType
{
  @WebMethod(action="xmlns.oracle.com/odi/OdiInvoke/invokeScenario")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="xmlns.oracle.com/odi/OdiInvoke/invokeScenario", output="xmlns.oracle.com/odi/OdiInvoke/InvokePortType/invokeScenarioResponse")
  @WebResult(targetNamespace="xmlns.oracle.com/odi/OdiInvoke/", partName="part1",
    name="invokeScenarioResponse")
  public com.sfmta.websvcs.applyratexml.types.CommandResultType invokeScenario(@WebParam(targetNamespace="xmlns.oracle.com/odi/OdiInvoke/",
      partName="part1", name="invokeScenarioRequest")
    com.sfmta.websvcs.applyratexml.types.InvokeScenarioRequest part1);
}
